name: Release Builder

on:
  workflow_dispatch:
  release:
    types: [created, published, edited] # Trigger on release creation, publication, or edit

permissions:
  contents: write
  packages: write
  actions: read


jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit  # Reuse all secrets from parent
    permissions:
      contents: write

  upload-apk:
    name: Upload to GitHub Release
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          path: app-release.apk/
          name: app-release.apk

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}