name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - dev
      - try-build
env:
  KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Set executable permissions for gradlew
        run: chmod +x android/gradlew
      - name: Decode and save keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | tr -d '\n' | base64 --decode > android/test.jks
      - name: ls -l
        run: |
          ls -l android/test.jks
          file android/test.jks
          echo "Keystore file created successfully!"
      - name: Set permissions for keystore
        run: chmod 600 /app/android/test.jks
      - name: Debug environment variables
        run: |
          if [ -z "$KEYSTORE_PASSWORD" ]; then echo "❌ KEYSTORE_PASSWORD is missing"; fi
          if [ -z "$KEY_ALIAS" ]; then echo "❌ KEY_ALIAS is missing"; fi
          if [ -z "$KEY_PASSWORD" ]; then echo "❌ KEY_PASSWORD is missing"; fi
      - name: Build project
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
      - name: Confirm build
        run: |
          echo "Build completed successfully!"
            echo "Checking for APK file..."
            if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
                echo "APK file found!"
                else
                echo "APK file not found!"
                exit 1
                fi
